deploy:
  release: ASM-v$(appveyor_build_version)
  description: 'Automatic release'
  provider: GitHub
  auth_token:
    secure: wATY3X+tJutkWJAYQcVl7S0g2vxAfA7GicBKnDOHVuODeCme9wm3UKjqzSvfdbkx
  draft: false
  prerelease: true
  artifact: ASM\CPUAssembler\bin\Debug\CPUAssembler.exe
  on:
    appveyor_repo_tag: true        # deploy on tag push only